import esbuild from "esbuild";
import fs from "fs";
import path from "path";
import builtins from "builtin-modules";

const banner = `/*\nTHIS IS A GENERATED/BUNDLED FILE BY ESBUILD\n*/\n`;

const prod = process.argv[2] === "production";
const outdir = "dist";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: path.join(outdir, "main.js"),
  minify: prod,
});

async function copyAssets() {
  if (!fs.existsSync(outdir)) fs.mkdirSync(outdir);
  fs.copyFileSync("manifest.json", path.join(outdir, "manifest.json"));
  if (fs.existsSync("styles.css")) {
    fs.copyFileSync("styles.css", path.join(outdir, "styles.css"));
  }
}

if (prod) {
  await context.rebuild();
  await copyAssets();
  process.exit(0);
} else {
  await context.watch();
  await copyAssets();
}
